name: bible_io_references
description: Parse, format, serialize, and extract multilingual Bible references and rich passage expressions with Unicode and OSIS/USFM support.
version: 1.1.0
homepage: https://github.com/m0ty/bible-io-references-dart
repository: https://github.com/m0ty/bible-io-references-dart
issue_tracker: https://github.com/m0ty/bible-io-references-dart/issues
documentation: https://github.com/m0ty/bible-io-references-dart#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

topics:
  - bible
  - parsing
  - references
  - scripture
  - osis

executables:
  bible_io_references: bible_io_references

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
